# Generated by Django 3.0.6 on 2020-07-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_registerstudent_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerstudent',
            old_name='picture',
            new_name='pictures',
        ),
    ]
